Carga y Procesamiento de Datos

In [16]:
import pandas as pd
import numpy as np

# Carga de archivos
df = pd.read_csv('../data/retail_sales_dataset.csv')

# Comprobamos la carga
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [ ]:
# Procesamiento de datos
print("Últimas 5 filas:")
display(df.tail()) #usamos display para mostrar el resultado de cada función
print("Información del DataFrame:")
display(df.info())
print("Estadísticas descriptivas:")
display(df.describe())
print("Tipos de datos:")
display(df.dtypes)
print("Número de filas y columnas:", df.shape)

Últimas 5 filas:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

Información del DataFrame:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

None

Estadísticas descriptivas:

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

Tipos de datos:

Transaction ID      int64
Date                  str
Customer ID           str
Gender                str
Age                 int64
Product Category      str
Quantity            int64
Price per Unit      int64
Total Amount        int64
dtype: object

Número de filas y columnas: (1000, 9)

Exploración de Datos con Numpy

In [ ]:
# Convertimos las colummnas a arrays de numpy
categorias_array = df['Product Category'].values
ventas_array = df['Total Amount'].values
fechas_array = df['Date'].values

# Valores únicos de categorías
categorias_unicas = np.unique(categorias_array)

# Calculamos días totales
dias_totales = np.unique(fechas_array).size

# Lista para almacenar resultados y econtrar max y min
lista_totales = []

# Exploramos por categoría
for cat in categorias_unicas:
    # Total de ventas por categoría
    total_ventas = np.sum(ventas_array[categorias_array == cat])
    lista_totales.append(total_ventas) #Guardamos el resultado en la lista
    
    # Promedio diario de ventas por categoría
    promedio_diario = total_ventas / dias_totales
    
    # Imprimimos resultados por categoría
    print(f"Categoría '{cat}': ")
    print(f"    Total de ventas: {total_ventas}")
    print(f"    Promedio diario: {promedio_diario:.2f}")
    print("-" * 50)

# Categorías de productos con mayores y menores ventas
max_ventas = np.max(lista_totales)
min_ventas = np.min(lista_totales)

# Usamos índices para encontrar las categorías correspondientes
categoria_max = categorias_unicas[np.argmax(lista_totales)]
categoria_min = categorias_unicas[np.argmin(lista_totales)]

# Imprimimos los resultados min y max
print(f"La categoría que más ventas tiene: {categoria_max} con {max_ventas}")
print(f"La categoría que menos ventas tiene: {categoria_min} con {min_ventas}")

Categoría 'Beauty':
    Total de ventas: 143515
    Promedio diario: 415.99
--------------------------------------------------
Categoría 'Clothing':
    Total de ventas: 155580
    Promedio diario: 450.96
--------------------------------------------------
Categoría 'Electronics':
    Total de ventas: 156905
    Promedio diario: 454.80
--------------------------------------------------
La categoría que más ventas tiene: Electronics con 156905
La categoría que menos ventas tiene: Beauty con 143515

Manipulación de Datos

In [42]:
# Filtramos por categoría 'Electronics'
filtro_electronics = categorias_array == 'Electronics'
ventas_electronics = ventas_array[filtro_electronics]

#  Operaciones en los datos para obtener estadísticas adicionales
# Impuestos (Multiplicación)
iva = np.sum(ventas_electronics) * 0.19

# Monto neto (Resta)
monto_neto = np.sum(ventas_electronics) - iva

# Cargo por envío (Suma)
cargo_envio = np.sum(ventas_electronics) + 5.00

# Porcentaje del total de ventas (División)
total_ventas = np.sum(ventas_array)
total_ventas_electronics = np.sum(ventas_electronics)
porcentaje_ventas = (total_ventas_electronics / total_ventas) * 100

# Imprimimos resultados
print("Cálculos para la categoría 'Electronics':")
print(f" - Total de ventas: {np.sum(ventas_electronics)}")
print(f" - Impuestos: {iva:.2f}")  
print(f" - Monto neto: {monto_neto:.2f}")
print(f" - Cargos por envío: {cargo_envio}")
print(f" - Porcentaje del total de ventas: {porcentaje_ventas:.2f}%")

Cálculos para la categoría 'Electronics':
 - Total de ventas: 156905
 - Impuestos: 29811.95
 - Monto neto: 127093.05
 - Cargos por envío: 156910.0
 - Porcentaje del total de ventas: 34.41%